[project]
name = "venture_menu"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/Users/olbing/.clarinet/cache"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.menu]
path = "contracts/menu.clar"
depends_on = []

[contracts.scratch-paper]
path = "contracts/scratch-paper.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
